### ISSUE TITLE
Missing } in lcd.c

### ISSUE THREAD

**Issue by thecky** [Sylaina/oled-display#1]
Hi,

you need to insert a "}" between the two #endif in lcd.c:
https://github.com/Sylaina/oled-display/blob/08ceb8e31b15ea1d2df0e3fdb9c00b869d9bc877/lcd.c#L353-L363

Without this "}" the function lcd_display isn't complete and the compiling run will fail (in graphicmode).

Regards,
Thomas

**Comment by Sylaina** [comment]
It is fixed. Thanks for tipp
