### ISSUE TITLE
TWBR out of range error and F_CPU undeclared

### ISSUE THREAD

**Issue by Huruvarshan** [Sylaina/oled-display#10]
I'm getting an error of the **TWBR** being **out of range** and the F_CPU being undelcared. 
TWBR out of range: I've tried setting the prescaler to 1, 4, 16 and 64. Aswell as changing the I2C frequency. Nothing worked for me. 
I am using the **AtMega2560** with an **external clock of 16MHz**. 

Here is a screenshot of the error list in Microchip Studio: 
![image](https://user-images.githubusercontent.com/112094724/221871508-db0961da-0a76-43ef-90b5-f710b1afab66.png)

**Comment by setEntwicklung** [comment]
It looks like you haven't declare F_CPU. TWBR will be calculated by F_CPU.
