### ISSUE TITLE
AVR 128DA48

### ISSUE THREAD

**Issue by rakshi-1988** [Sylaina/oled-display#12]
Hi,

We are using this oled library with AVR128DA48, i don't think it's working,
We are using I2C library from  [https://github.com/cv007/Avr01Dx_Twi](url) The I2C EEPROM works perfectly fine with this library.
Need your support on this, Tried with Both address 0x3C and 0x78.
In I2C scan my display shows 0x3C address
Many Thanks

**Comment by Sylaina** [comment]
You have to check your controller at display. Is it a SSD1306 (typical for 0.96" displays) or its a SH1106 (typical for 1.3" displays)? The default controller-typ is SH1106 but your I2C-address is typical for a SSD1306, change #define at line 61 in lcd.h from SH1106 to SSD1306 and try it again. ;)
