### ISSUE TITLE
Works initial but then...

### ISSUE THREAD

**Issue by pauledd** [Sylaina/oled-display#2]
Hi

I tried your code with Arduino IDE 1.8.5 on an Atmega328 running at 1Mhz and 3.3V
git cloned your repo to Arduino/libraries
changed in i2c.h: #define F_I2C			50000UL// clock i2c
changed in lcd.h: #define SSD1306 , #define LCD_I2C_ADR         (0x78 >> 1)
wrote a sample sketch:

```
#include "lcd.h"
#define F_CPU 1000000UL;

void setup() {
  lcd_init(LCD_DISP_ON);
}

void loop() {
  lcd_puts("Hello World");  // put string from RAM to display (TEXTMODE) or buffer (GRAPHICMODE)
  lcd_gotoxy(0,2);          // set cursor to first column at line 3
  lcd_puts_p(PSTR("String from flash"));  // puts string form flash to display (TEXTMODE) or buffer (GRAPHICMODE)
#if defined GRAPHICMODE
  lcd_drawCircle(64,32,7,WHITE); // draw circle to buffer
  lcd_display();                  // send buffer to display
#endif
}
```
Text is displayed as expected. But quite dim compared to Adafruit SSD1306 library...
Then I modified the sketch to:
```
#include "lcd.h"
#define F_CPU 1000000UL;

void setup() {
  lcd_init(LCD_DISP_ON);
}
void loop() {
  lcd_puts("Oma");
}
```
After flashing the display restarts but displays again the text from the first sketch.
What I am doing wrong?
Whats the difference between "put string from RAM to display" and "puts string form flash to display"?

**Comment by heikete** [comment]
To address your question first, in graphic mode this library doesn't operate directly on the display, but
creates a buffer and when all of the drawing has been finished it sends the buffer to the display chip,
replacing the image. The function which 'overwrites the image' is lcd_display(). You didn't call it so image was still the same.
About initial configuration I also found some differences comparing to other libraries.
The initial sequence is well described in python adafruit library:
[SSD1306.py](https://github.com/adafruit/Adafruit_Python_SSD1306/blob/master/Adafruit_SSD1306/SSD1306.py)

I believe that some options need conditional values. My 128x32 display had every odd line missing (display showed only even rows without any blank ones) I adjusted init sequence according to the relevant section of
aforementioned python library and it worked.

Here's my initialization for 128x32. NOTE: 0xDA parameter should be 0x12 for 128x64:
```
const uint8_t init_sequence [] PROGMEM = {    // Initialization Sequence
    LCD_DISP_OFF,    // [ Display OFF ]
    0x20, 0b00,      // [ Addressing mode ] 0 horiz., 1 vert
    // 00=Horizontal Addressing Mode; 01=Vertical Addressing Mode;
    // 10=Page Addressing Mode (RESET); 11=Invalid
    0xC8,            // [ Com scan direction ] inc: 0xC0, dec: 0xC8
    0x00,            // --set low column address
    0x10,            // --set high column address
    0x40,            // --set start line address
    0x81, 0x3F,      // Set contrast control register
    0xA1,            // [ Seg Remap ] 0xA1=address 127 mapped.
    0xA6,            // [ Display mode ] Normal: 0xA6, Inverse: 0xA7
    0xA8, 0x1F,      // [ Multiplex ratio ] Set multiplex ratio(1 to 64)
    0xA4,            // [ Output RAM to display ] Yes: 0xA4, no: 0xA5
    0xD3, 0x00,      // [ Display offset ] 0x00 -> no offset
    0xD5, 0x80,      // [ Divide ratio ] suggested value: 0x80
    0xD9, 0xF1,      // Set pre-charge period
    0xDA, 0x02,      // Set com pins hardware configuration << for 128x64 should be 0x12
    0xDB, 0x40,      // [ Vcom detect ]
    0x8D, 0x14       // Set DC-DC enable
};  
```
