### ISSUE TITLE
Issue with the code

### ISSUE THREAD

**Issue by ghost** [Sylaina/oled-display#6]
So I tried to use my 128x64 I2C OLED with an Arduino and it worked without a problem. I really wanted to use pure C code so I came across your library. I tried running it on my ATMEGA328P but this is what I got.
![image](https://user-images.githubusercontent.com/34149262/65012352-da10b700-d8cb-11e9-81de-72e4681494e9.png)

**Comment by Sylaina** [comment]
Wich controller have you configured in lcd.h (line 61)? It looks like configured for SH1106 controller/display (default when you download library from github) and you use a SSD1306 controller/display.

**Comment by ghost** [comment]
Yes I am indeed using a SSD1306. What are the things that I need to change in that header file so that it works on the SSD1306 controller?

**Comment by Sylaina** [comment]
You have to replace "#define SH1106" by "#define SSD1306" in lcd.h (line 61 in actual version that updated today)

**Comment by ghost** [comment]
It worked now. Another thing I have to change is the LCD_I2C_ADR to 0x78 so that it get directed to the 0X3C address. Thanks for the help!
![image](https://user-images.githubusercontent.com/34149262/65174979-d2a1f880-da06-11e9-8dba-adf0e23b4ac8.png)

**Comment by joaoantoniocardoso** [comment]
Maybe this issue could be in a FAQ? This is not obvious by reading the example...

**Comment by Sylaina** [comment]
> Maybe this issue could be in a FAQ? This is not obvious by reading the example...

Ähm...why not clear from TODOs in header-file of lcd-library? All TODOs in the header files tells you, what you have to do for running display. Your prefered IDE should show you all TODOs.

**Comment by joaoantoniocardoso** [comment]
Sorry, but try to consider that I am not the only one thinking this way:
the TODO word is commonly used to document what should be implemented next
by the development team.

For example it is not clear if the programmer (your client) should expect
the library to work with graphical by changing the respective macro
definition because the one maybe thinks TODO is something to be developed.

I like the way this lib is implemented, it is really simple to integrate,
but I think the documentation can be improved. Thanks!

**Comment by 19danny94** [comment]
Had the same Issue... I tried different Controllers etc...and now after 4 hours, I read your Issue.
Should really be in the description of the Lib. Overall its pretty nice an working well now.

PS: You could add the defined(__AVR_ATmega32__)|| to your lib, cause its working well and has the same registers.
